name: explainable-ai-bioink-design
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - xgboost
  - shap
  - openpyxl
  - joblib
  - ipython
  - jupyterlab
  - nbformat
  - pip
